usage: opensource

environment_variables:
  MUTANT: "true"

integration:
  name: minitest

includes:
  - lib
  - test

requires:
  - http/form_data

mutation:
  timeout: 10.0
  operators: full

matcher:
  subjects:
    - HTTP::FormData*
