plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

inherit_from:
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/style.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.2
