inherit_from:
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/minitest.yml
  - .rubocop/style.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.2
