inherit_from:
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/style.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.5
  DefaultFormatter: fuubar
