# Type signatures for the http-form_data gem

module HTTP
  module FormData
    CRLF: String

    class Error < StandardError
    end

    type formdata = Multipart | Urlencoded

    # Selects encoder type based on given data
    def self.create: (untyped data, ?encoder: _Encoder?) -> formdata

    # Coerces obj to Hash
    def self.ensure_hash: (untyped obj) -> Hash[untyped, untyped]

    # Coerces obj to an Enumerable of key-value pairs
    def self.ensure_data: (untyped obj) -> untyped

    private

    # Checks if data contains multipart data
    def self.multipart?: (untyped data) -> bool

    interface _Encoder
      def call: (untyped data) -> String
    end
  end
end
